import { Inter, Hind_Siliguri } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const hindShiloguri = Hind_Siliguri({ subsets: ['latin'], weight: ['300', '400','500', '600','700'] }); 

export const metadata = {
  title: "24 hours of a muslim ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={hindShiloguri.className}>{children}</body>
    </html>
  );
}
